### PR TITLE
[feat] Create Basic Inputs.

### PR DESCRIPTION
**Pull request by kennyw12**

### CODE REVIEW

**Comment by atomanyih** [comment]
Thanks for the PR!

Some notes:
- it would be nice if the docs explained and showed examples of using this with other input types
- maybe the docs should be under `forms` like on the CSS side? (@pivotal-plech ?) 
- the dependencies in `package.json` are wrong

Also a question: What's the use case for passing children in? Errors?

I'll probably make these changes whenever we pull this in, unless you do it first

**Comment by pivotal-plech** [comment]
I agree, it would make the most sense to be consistent with organization on the CSS side.

**Comment by nicw** [comment]
@kennyw12 any update for this PR? Given the team's availability, we won't likely be able to tackle this from our side. If you can reply to August's questions and update the PR, that'd be great!

**Comment by kennyw12** [comment]
@atomanyih 

There isn't really a use case for children. We decided to have error messaging as props.
I'll update the docs. 
These inputs have changed quite a bit. I made a WIP commit to show the new changes. 
 - There is a EmailInput that uses a tooltip to show if the email is invalid. However, that tooltip relies on OverlayManual. I'll make a separate PR for that. I'll also create another PR for just BasicInputs in case EmailInput or OverlayManual isn't desired.

I'll close this PR and try to organize this better with a BasicInputs PR and OverlayManual PR for now.

**Pull request closed without merging**
