### PR TITLE
Add 'disabled' property for dropdown

### PR DESCRIPTION
**Pull request by yangru**
Hi,
I am using pivotal-ui, it's good and meet the requirements most of the time. 
But when I use Dropdown, I can't make it disabled, so I have to use another component (Input) to replace it when disabled is needed.

To make things simple, I want to add this "disabled" property to Dropdown component.
Please review the code.

### CODE REVIEW

**Comment by sweinstein22** [comment]
Hi @yangru ,
For accessibility reasons it's actually preferable to replace disabled dropdowns and inputs with text - screen readers will skip over a disabled fields which isn't ideal for people who have visual impairments. Would it be possible to do that in your use case? We can take your feedback and add some documentation to this affect.

**Comment by yangru** [comment]
Hi, @sweinstein22,

Thank you for your reply, I see your concerns.

This is our story:
Our product is mainly for those who don't have visual impairments. And our design (made by our designer, not me) has 2 modes: edit and view. When view mode, we'd like to keep the inputs and dropdowns there but disabled, so that users know it's clickable and can be changed. 

And I think the original input and select (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) provide a "disabled" property for a reason, a library is responsible for providing the basic properties, it's the developer's choice to use it or not (depend on the use case). 

And I've also used some other good libraries like bootstrap and ant design, their dropdowns provide the "disabled" property, like:
https://react-bootstrap.github.io/components/dropdowns/
https://ant.design/components/select/
I don't think we are not better then them. so we NEED provide this property.

I'm not professional on accessibility, but do consider my suggestion and be free to make any change to make it more user-friendly for people who have visual impairments. 

However, it's still ok to be without disabled property, but please don't disable the  Input's "disabled" property. This is my last resort.


> Hi @yangru ,
> For accessibility reasons it's actually preferable to replace disabled dropdowns and inputs with text - screen readers will skip over a disabled fields which isn't ideal for people who have visual impairments. Would it be possible to do that in your use case? We can take your feedback and add some documentation to this affect, and maybe change the disabled behavior of our Input component.
> 
> It's also worth noting that dropdowns should only be used for navigation, so it seems odd to me that you would want to have it disabled, the use case you're describing seems more like the behavior of select.

**Comment by yangru** [comment]
Hi, @sweinstein22,

Thank you for your reply, I see your concerns.

This is our story:
Our product is mainly for those who don't have visual impairments. And our design (made by our designer, not me) has 2 modes: edit and view. When view mode, we'd like to keep the inputs and dropdowns there but disabled, so that users know it's clickable and can be changed. 

Select is not beautiful enough, so we use dropdown most of the time.

And I think the original input and select (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) provide a "disabled" property for a reason, a library is responsible for providing the basic properties, it's the developer's choice to use it or not (depend on the use case). 

And I've also used some other good libraries like bootstrap and ant design, their dropdowns provide the "disabled" property, like:
https://react-bootstrap.github.io/components/dropdowns/
https://ant.design/components/select/
I don't think we are not better then them. so we NEED provide this property.

I'm not professional on accessibility, but do consider my suggestion and be free to make any change to make it more user-friendly for people who have visual impairments. 

However, it's still ok to be without disabled property, but please don't disable the  Input's "disabled" property. This is my last resort.

> Hi @yangru ,
> For accessibility reasons it's actually preferable to replace disabled dropdowns and inputs with text - screen readers will skip over a disabled fields which isn't ideal for people who have visual impairments. Would it be possible to do that in your use case? We can take your feedback and add some documentation to this affect, and maybe change the disabled behavior of our Input component.
> 
> It's also worth noting that dropdowns should only be used for navigation, so it seems odd to me that you would want to have it disabled, the use case you're describing seems more like the behavior of select.

**Comment by sweinstein22** [comment]
After discussing things with other maintainers, we're going to keep the dropdown in its current state without a 'disable' option.  While we do try to maintain a level of flexibility, we also value enforcing a base level of inclusivity, regardless of aesthetic preferences, and are trying to help those who use the library to be accessible by default. We appreciate the feedback you've provided.

**Pull request closed without merging**
