### PR TITLE
feat(styleguide): shiny new intro page

### PR DESCRIPTION
**Pull request by pivotal-plech**
Hey @gpleiss @matt-royal, check out the shiny new intro page! Particularly, is the if statement on line 77 of _header.html alright?

Thanks!

### CODE REVIEW

**Comment by gpleiss** [comment]
Love the logo!

For the top of the page: @gpleiss: I do like how attention-grabbing the landing page is. However, on first visit, @matt-royal and I thought the blue container was the whole page. There's no indication to scroll down to see more content. Also, having the "Try Now" button take you to github is a strange first action. Maybe that could be at the bottom of the page? @gpleiss thinks that a better first action would be a "see it in action" link to an example app. @matt-royal thinks maybe a link to styleguide pages

For the "Getting Started" section: the instructions are for the monolith. Do we want them to be for consuming modules instead? (If we want to stick to monolith instructions, the "download the latest release" should be a link).

For the "How to use this styleguide" section, @matt-royal reads the blue and white icons as "ignore this, it's a footer". A variety of colors or at least a more attention-grabbing color would help. @gpleiss expected them to be links

For the "What's Included" section: @gpleiss wants to scrap it. I find it confusing, especially since most of the stuff is to be deprecated. At the very least, can we not squish the best practices and the what's included sections together?

@gpleiss: where's pivotal gary? I think the "built w/ pivotal ui" section is probably the most important section for the landing page - especially if this page is going to be used for advertisement at CSS conf.

**Comment by pivotal-plech** [comment]
@gpleiss @matt-royal 

Agree on all fronts. I'm more concerned in the short-term with getting the link to the PCF Product Design job req before Thursday as we'll be distributing our fancy stickers to all the fancy designers.

I'm down for removing the "What's Included" section short term as that would clean it up a bit and removing things is really easy...

All the rest I think we can punt on for a later revision? We are like agile, right?

@stubbornella Thoughts?

**Comment by stubbornella** [comment]
Yeah, I agree with almost all the feedback, but we are out of time for this week. (To be fair, we only decided to sponsor the conference on Friday, so we knew time was short). Let's push what we have, and then iterate on some of the smaller things as we can. I'm comfortable making text-only changes until after the conference, so we don't risk breaking things.

**Comment by gpleiss** [comment]
Also - the logo in the nav bar needs to be updated to the new one.

**Pull request merged**
