### PR TITLE
fix(alerts): Remove extra margin on the alert

### PR DESCRIPTION
**Pull request by charleshansen**
When the close button is followed by a media component, the margin
should be cleared. There is a special rule that handled this for alerts
inside a table which is how it is shown in the styleguide.

### CODE REVIEW

**Comment by stubbornella** [comment]
Notes after speaking to @rdy and @tylerphelan: 

Making the media block display differently inside an alert is a little hacky. Instead, let's add the class `ptn` to the Media element when it is inside an alert. This will need to be done for the React component (change in one place and it will propagate everywhere) and for the CSS component which will need to have every instance updated by hand. Unfortunately, that makes it a breaking change, but probably teams have already added the spacing class since it would have been broken in their apps.

Can you update the PR?

I'll make a note to look at the table spacing CSS rule that allowed this bug not to show in the styleguide.

**Comment by rdy** [comment]
@stubbornella sure thing, we will amend the pull request as you have outlined above.

**Comment by stubbornella** [comment]
We realized today this should have been a `.mtn` not a `.ptn`.

**Comment by atomanyih** [comment]
You don't need to interpolate the className on Media - it's just a string. But that's a minor thing.

Ready for merge, @stubbornella

**Pull request merged**
