### PR TITLE
Add Dark Type Modifiers to Documentation

### PR DESCRIPTION
**Pull request by pivotal-plech**
Simply adding the modifiers to the big color class table.

---
Add color modifiers to the table of all the color classes to the
styleguide.

[#99441746]

### CODE REVIEW

**Comment by pivotal-plech** [comment]
@stubbornella @matt-royal Could you take a quick peek?

**Comment by stubbornella** [comment]
This looks good to me. For the change log we need to provide a translation for teams already using the dark classes. Did you add that to your commit message for the original color modification story?

e.g.

```
If you were using:                           replace it with: 
$type-dark-1                                   $type-dark-2
```

**Comment by stubbornella** [comment]
(those replacement values are made up, of course, but you see what I mean? We need to tell teams how to manage upgrading to PUI 2.0)

**Comment by stubbornella** [comment]
I merged this for now and made a separate story for the conversion chart.

**Pull request merged**
