### PR TITLE
ES6 styleguide and various cleanups

### PR DESCRIPTION
**Pull request by jadekler**
Needs a one-over

### CODE REVIEW

**Comment by jadekler** [comment]
And apparently a rebase haha

**Comment by jadekler** [comment]
@charleshansen I had an `module not found internal/fs` problem with `npm install` that I resolved with `rm -rf node_modules`, but otherwise everything on this branch seemed fine locally (on machine `boyhood`).

**Comment by charleshansen** [comment]
It does not compile all the way. It looks like you need to keep the extra lines in the `react_example_table`s

**Comment by jadekler** [comment]
@charleshansen Fixed

**Comment by charleshansen** [comment]
Looks 99% good. The expander example is broken though. 

Also, we need to merge with the panel props change.

**Comment by jadekler** [comment]
@charleshansen Fixed! Let me know if this looks good.

**Pull request merged**
