### PR TITLE
fix HTML syntax for css example

### PR DESCRIPTION
**Pull request by mikfreedman**

### CODE REVIEW

**Comment by atomanyih** [comment]
Things I've learned today: 

The [link element](http://www.w3.org/TR/html5/document-metadata.html#the-link-element) is a [void element](http://www.w3.org/TR/html5/syntax.html#void-elements) which `only have a start tag; end tags must not be specified`

So I think it was valid as `<link>`. Most examples seem to have it that way, and the chrome inspector renders it like that as well

For what it's worth, w3's parsing rules [for link](http://www.w3.org/TR/html5/syntax.html#parsing-main-inhead) say `Acknowledge the token's self-closing flag, if it is set` so maybe it's valid either way.

**Comment by mikfreedman** [comment]
@atomanyih this is a weird one, Spring refuses to parse the document unless I add the tags. maybe I should raise an issue with the,?

**Comment by atomanyih** [comment]
@mikfreedman Is this still a problem? If it is, we'll just pull it in

**Comment by mikfreedman** [comment]
@atomanyih  We've gone a different direction. thanks!

**Pull request closed without merging**
