### PR TITLE
Updating alert and autocomplete docs to es6

### PR DESCRIPTION
**Pull request by jadekler**
@charleshansen @rdy es6 seems to work fine with the current hologram setup. Note the following renders just fine: 

```
const onPick = item => alert('You selected ' + item.value);
const onInitializeItems = callback => callback(['foo', 'food', 'bar']);
const AutocompleteExample = () => <Autocomplete onInitializeItems={onInitializeItems} onPick={onPick}/>;

<AutocompleteExample/>
```

### CODE REVIEW

**Comment by jadekler** [comment]
For reference, I'm using the [react doc style](https://facebook.github.io/react/docs/introducing-jsx.html) of writing view components as single functions with helper functions living in the same file (as opposed to the class/object/createClass styles of an encompassing object).

**Comment by charleshansen** [comment]
Looks good in general. I do like the new style for this component, since it doesn't have any real instance methods. I think we can stop using `createClass` and reserve `class` for cases that really need it.

Do you want me to merge this or do you want to have a better plan about switching to es6 documentation before we start this? I'm happy either way, I just don't want to end up with only 1 es6 example for the next release.

**Comment by jadekler** [comment]
@charleshansen Cool! Yeah this PR is more just to get some thoughts. If you're cool with this style I'll go through and begin updating the rest of the docs

**Comment by charleshansen** [comment]
Yeah, I like the style. There are a couple components that are complicated and we will have to look over (like Modals), but I think most should be straightforward. For what it is worth, I think I will hold off on actually merging until we publish 7.3 (it just makes git easier). That said, consider the commit approved if you want to update the rest of the docs.

**Comment by charleshansen** [comment]
Also, this PR did not address the require/import syntax. I'm still not 100% sure what we should do there (I kinda like `const {Button} = require('pui-react-buttons')`), that should be considered a separate story for now.

**Comment by jadekler** [comment]
@charleshansen Good point, I'll take that out so that we can address it separately. I'm pretty pro-import, given that it's in the [JS spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and [actively being implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=568953) and [react](https://facebook.github.io/react/docs/installation.html) and [redux](https://github.com/reactjs/redux) docs favor it.

I think it's pretty jarring for people to see a react library go against the convention used elsewhere.

**Comment by jadekler** [comment]
Closing this PR and re-creating once all docs are g2g

**Pull request closed without merging**
