### PR TITLE
Add missing package.json packages

### PR DESCRIPTION
**Pull request by jadekler**
Signed-off-by: Hunter Williams <huwilliams@pivotal.io>

`pivotal-ui/library` errors we saw:

```
±  |development → origin ✓| → gulp
module.js:327
    throw err;
    ^

Error: Cannot find module 'event-stream'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pivotal/workspace/pivotal-ui/library/tasks/accessibility.js:3:1)
    at Module._compile (module.js:409:26)
    at loader (/Users/pivotal/workspace/pivotal-ui/library/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pivotal/workspace/pivotal-ui/library/node_modules/babel-core/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

```
±  |development → origin U:1 ✗| → gulp
module.js:327
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pivotal/workspace/pivotal-ui/library/node_modules/strong-wait-till-listening/index.js:7:13)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pivotal/workspace/pivotal-ui/library/node_modules/babel-core/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

`pivotal-ui/styleguide` errors we saw:

```
±  |development → origin U:1 ✗| → gulp
module.js:327
    throw err;
    ^

Error: Cannot find module 'event-stream'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pivotal/workspace/pivotal-ui/styleguide/tasks/css-critic.js:4:1)
    at Module._compile (module.js:409:26)
    at loader (/Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/babel-core/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/babel-core/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

```
 2016-11-10 10:11:40 ☆  |2.3.1| ironton in ~/workspace/pivotal-ui/styleguide
±  |development → origin U:2 ✗| → gulp
[10:11:51] Using gulpfile ~/workspace/pivotal-ui/styleguide/gulpfile.js
[10:11:51] Starting 'dev'...
[10:11:51] Starting 'setup-watchers'...
[10:11:51] Finished 'setup-watchers' after 45 ms
[10:11:51] Starting 'styleguide-build'...
[10:11:51] Starting 'styleguide-clean'...
[10:11:51] Finished 'styleguide-clean' after 3.62 ms
[10:11:51] Starting 'hologram'...
[10:11:51] Starting 'build-sass'...
[10:11:52] Starting 'build-js'...
[10:11:52] Starting 'import-bootstrap-js'...
[10:11:52] Starting 'styleguide-assets'...
[10:11:52] Starting 'prism-assets'...
[10:11:52] Starting 'copy-old-styleguides'...
[10:11:52] Finished 'copy-old-styleguides' after 1.4 ms
[10:11:53] Finished 'import-bootstrap-js' after 866 ms
[10:11:53] Finished 'build-sass' after 1.16 s
[10:11:53] Finished 'prism-assets' after 887 ms
[10:11:59] Finished 'hologram' after 8.07 s

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./~/pui-react-modals/modals.js
Module not found: Error: Cannot resolve module 'classnames' in /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/pui-react-modals
resolve module classnames in /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/pui-react-modals
  looking for modules in /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules
    /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames doesn't exist (module as directory)
    resolve 'file' classnames in /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules
      resolve file
        /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames doesn't exist
        /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames.webpack.js doesn't exist
        /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames.web.js doesn't exist
        /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames.js doesn't exist
        /Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames.json doesn't exist
[/Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames]
[/Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames]
[/Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames.webpack.js]
[/Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames.web.js]
[/Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames.js]
[/Users/pivotal/workspace/pivotal-ui/styleguide/node_modules/classnames.json]
 @ ./~/pui-react-modals/modals.js 43:17-38
```

### CODE REVIEW

**Comment by jadekler** [comment]
Ps @charleshansen how is CI green without this? This issue came up the first time we did a `gulp` within `pivotal-ui/library`. Are there some globally installed npm installed libraries on CI?

**Comment by charleshansen** [comment]
Kinda confused about this pull request, there are a lot of similarities to https://github.com/pivotal-cf/pivotal-ui/pull/434  I think I'd take the package.json updates though

**Comment by jadekler** [comment]
@charleshansen This is our fault - we had accidentally `git co -b` from non-dev branch 😞  Will fix

**Comment by jadekler** [comment]
Closing this as it's pretty trivial stuff

**Pull request closed without merging**
